### PR TITLE
DAIL-SQL

### PR DESCRIPTION
**Pull request by BeachWang**

### CODE REVIEW

**Comment by BeachWang** [comment]
Hi Dr. Tao,
We have updated the spiders.md file with our tested execution accuracy in leaderboard. It is now ready to be merged. Thank you!

**Comment by taoyds** [comment]
Hi - Sorry for the delay. It seems that 69 files have been modified in your PR. Could you please double check that or submit a new PR instead? Thanks.

**Comment by BeachWang** [comment]
Hi Dr. Tao,

Sorry for my mistake to submit the .idea file in last PR. We have summitted the spider.md in another PR. It is now ready to be merged. Thank you!

**Comment by BeachWang** [comment]
Hi Dr. Tao,

We have resubmitted the spider.md in another PR. It is now ready to be merged. Thank you!

**Pull request closed without merging**
